development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5

test:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: sickpanos_production
  pool: 5
  host: ec2-107-21-187-54.compute-1.amazonaws.com
 