development:
  adapter: postgresql
  encoding: unicode
  database: sickpanos_development
  host: localhost
  pool: 5
  username: christopheroentojo

test:
  adapter: postgresql
  encoding: unicode
  database: sickpanos_test
  host: localhost
  pool: 5
  username: christopheroentojo