development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5

test:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: sickpanos_production
  pool: 5
  username: christopheroentojo
  password:
 